# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "468869026551455874d932a9608b7494"
name = "BloatBuster: Clean Theme Code"
application_url = "https://example.com"
embedded = true
handle = "bloatbuster-clean-theme-code"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[pos]
embedded = false
