# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f3c6dde5474766c85897a2bd2567ea50"
name = "BloatBuster: Clean Theme Code"
application_url = "https://bloatbuster.relayworks.dev"
embedded = true
handle = "bloatbuster-clean-theme-code"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "/webhooks/compliance"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://bloatbuster.relayworks.dev/auth/callback" ]

[pos]
embedded = false
